### ISSUE TITLE
Mapinfo Drivers

### ISSUE THREAD

**Issue by stev-0** [sethfitz/heroku-buildpack-gdal#1]
Any idea why these are not loading? I am using this with node-gdal and on running 
`console.log(gdal.drivers.getNames());` Mapinfo or TAB doesn't appear anywhere in the list despite it being included in the GDAL version and seemingly not being removed from the compilation..

**Comment by sethfitz** [comment]
Is `node-gdal` using the bundled binary or do you see it compiling against GDAL from the buildpack?

If you want to ensure that it's compiling against the buildpack GDAL, you need something along the lines of [--build-from-source=gdal](https://github.com/mapbox/node-pre-gyp/issues/58).

Alas, I think `node-gdal` requires 2.x and 1.11(ish, I can't remember) is included here, so you may generally be out of luck.

**Comment by stev-0** [comment]
My bad, it wasn't compiling against this. Thanks
