### ISSUE TITLE
New build with gdal buildpack

### ISSUE THREAD

**Issue by jesseadamsnpgs** [sethfitz/heroku-buildpack-gdal#2]
It appears that this URL is no longer available: https://s3.amazonaws.com/mojodna-heroku/heroku-16/gdal-1.11.1-1.tar.gz

This means new builds with this build pack will fail.  Can the permissions on the build be updated for public access?

Thank you,

**Comment by sethfitz** [comment]
The most recent Heroku stack supported by this buildpack is `cedar-14`. The URL above is generated when trying to use it with the `heroku-16` stack.

Your options seem like they're: 1) use an older stack (if `cedar-14` is still supported by Heroku) or 2) create builds against a newer stack.

(Sorry, I haven't used Heroku in a few years and thus haven't had the need to update the buildpack.)
